### ISSUE TITLE
Finite map as semiring?

### ISSUE THREAD

**Issue by conal** [oisdk/semiring-num#1]
How did you choose the following `Semiring` instance for finite maps?

``` haskell
instance (Ord a, Monoid a, Semiring b) =>
         Semiring (Map a b) where
    one = Map.singleton mempty one
    {-# INLINE one #-}
    zero = Map.empty
    {-# INLINE zero #-}
    (<+>) = Map.unionWith (<+>)
    {-# INLINE (<+>) #-}
    xs <.> ys =
        Map.fromListWith
            (<+>)
            [ (mappend k l, v <.> u)
            | (k,v) <- Map.toList xs
            , (l,u) <- Map.toList ys ]
    {-# INLINE (<.>) #-}
```

It seems to suit languages as bags of strings (and other monoidal values), generalized from natural numbers as multiplicities. Also as generalized convolution.

**Comment by oisdk** [comment]
The semiring instance was effectively the minimal instance I could think of at the time, but "bags of strings" was indeed in my mind when I wrote it.

I hadn't realised, but yes it does indeed represent a generalized convolution: `Map (Sum Natural) a` is an encoding of sparse polynomials, with coefficients in `a`.

**Comment by conal** [comment]
Thanks for the reply! I've just started perusing your [blog posts](https://doisinkidney.com/). Lots of great stuff there, and I see we have substantial shared interests and taste.
