### ISSUE TITLE
Minimal definitions for StarSemiring

### ISSUE THREAD

**Issue by conal** [oisdk/semiring-num#3]
The `StarSemiring` class says `{-# MINIMAL star | plus #-}`, but it seems to me that the defaults for `star` and `plus` sometimes suffice as an implementation. What do you think of removing this `MINIMAL` pragma?

**Comment by oisdk** [comment]
Sounds good to me!

**Comment by conal** [comment]
Cool. Would you like a PR?

**Comment by oisdk** [comment]
That would be great! thanks!
